from __future__ import annotations

MESH_FAMILY_ORDER = [
    "props",
    "architecture",
    "foliage",
    "items",
    "characters_static",
    "enemies_static",
]

MESH_FAMILY_SPECS = {
    "props": {
        "id": "props",
        "label": "Props",
        "default_variant": "crate",
        "material_slots": ["wood", "metal"],
        "examples": [
            "chest",
            "crate",
            "barrel",
            "table",
            "chair",
            "rock",
            "campfire",
            "market_stall",
            "lantern_post",
            "shop_marker",
            "inn_marker",
            "enemy_spawn",
            "ice_crystal",
            "stone_tablet",
            "signal_brazier",
            "well",
            "fountain",
            "statue_plinth",
            "sign_post",
            "rubble_pile",
        ],
    },
    "architecture": {
        "id": "architecture",
        "label": "Architecture",
        "default_variant": "pillar",
        "material_slots": ["stone", "marble"],
        "examples": [
            "pillar",
            "arch",
            "wall_module",
            "shrine_marker",
            "obelisk",
            "crystal_altar",
            "ruin_gateway",
            "fortress_bastion",
            "tower_top",
            "dungeon_gate",
            "bridge_support",
            "defensive_wall",
            "gatehouse",
            "watchtower",
            "market_arch",
            "temple_steps",
        ],
    },
    "foliage": {
        "id": "foliage",
        "label": "Foliage",
        "default_variant": "tree",
        "material_slots": ["bark", "leaf"],
        "examples": [
            "tree",
            "bush",
            "deadwood",
            "sacred_shrub",
            "palm_tree",
            "highland_shrub",
            "cave_fungus",
            "snow_pine",
            "marsh_reed",
            "ancient_fern",
            "volcanic_rock_cluster",
            "coral_formation",
        ],
    },
    "items": {
        "id": "items",
        "label": "Items",
        "default_variant": "potion",
        "material_slots": ["glass", "metal", "crystal"],
        "examples": [
            "potion",
            "sword_icon_mesh",
            "relic_orb",
            "field_ration",
            "staff_icon_mesh",
            "medallion",
            "shield_icon_mesh",
            "armor_icon_mesh",
            "ring_icon_mesh",
            "gem_icon_mesh",
            "bow_icon_mesh",
        ],
    },
    "characters_static": {
        "id": "characters_static",
        "label": "Characters Static",
        "default_variant": "npc_humanoid",
        "material_slots": ["cloth", "leather", "metal"],
        "examples": [
            "npc_humanoid",
            "npc_guard",
            "npc_priest",
            "npc_merchant",
            "npc_elder",
            "npc_rebel",
            "npc_knight",
            "npc_sage",
            "npc_innkeeper",
            "npc_blacksmith",
            "npc_mage_static",
            "npc_thief",
        ],
    },
    "enemies_static": {
        "id": "enemies_static",
        "label": "Enemies Static",
        "default_variant": "enemy_beast",
        "material_slots": ["bone", "leather", "metal"],
        "examples": [
            "enemy_beast",
            "enemy_hunter",
            "enemy_sentinel",
            "enemy_mage",
            "enemy_undead",
            "enemy_golem",
            "enemy_elemental",
            "enemy_fiend",
            "enemy_dragon_static",
            "enemy_revenant",
            "enemy_serpent",
        ],
    },
}

MESH_VARIANT_SPECS = {
    "chest": {
        "family": "props",
        "label": "Chest",
        "material_slots": ["wood", "metal"],
        "parts": [
            {"kind": "box", "scale": (1.0, 0.55, 0.75), "offset": (0.0, -0.05, 0.0)},
            {"kind": "box", "scale": (1.0, 0.28, 0.82), "offset": (0.0, 0.38, 0.0)},
            {"kind": "box", "scale": (0.12, 0.42, 0.82), "offset": (-0.44, 0.12, 0.0)},
            {"kind": "box", "scale": (0.12, 0.42, 0.82), "offset": (0.44, 0.12, 0.0)},
        ],
    },
    "crate": {
        "family": "props",
        "label": "Crate",
        "material_slots": ["wood"],
        "parts": [
            {"kind": "box", "scale": (1.0, 1.0, 1.0), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.92, 0.06, 0.92), "offset": (0.0, 0.47, 0.0)},
        ],
    },
    "barrel": {
        "family": "props",
        "label": "Barrel",
        "material_slots": ["wood", "metal"],
        "parts": [
            {"kind": "prism", "scale": (0.82, 1.0, 0.82), "offset": (0.0, 0.0, 0.0), "sides": 8},
            {"kind": "box", "scale": (0.9, 0.08, 0.9), "offset": (0.0, 0.48, 0.0)},
            {"kind": "box", "scale": (0.9, 0.08, 0.9), "offset": (0.0, -0.48, 0.0)},
        ],
    },
    "table": {
        "family": "props",
        "label": "Table",
        "material_slots": ["wood"],
        "parts": [
            {"kind": "box", "scale": (1.4, 0.14, 0.9), "offset": (0.0, 0.55, 0.0)},
            {"kind": "box", "scale": (0.15, 0.95, 0.15), "offset": (-0.6, 0.0, -0.35)},
            {"kind": "box", "scale": (0.15, 0.95, 0.15), "offset": (0.6, 0.0, -0.35)},
            {"kind": "box", "scale": (0.15, 0.95, 0.15), "offset": (-0.6, 0.0, 0.35)},
            {"kind": "box", "scale": (0.15, 0.95, 0.15), "offset": (0.6, 0.0, 0.35)},
        ],
    },
    "chair": {
        "family": "props",
        "label": "Chair",
        "material_slots": ["wood"],
        "parts": [
            {"kind": "box", "scale": (0.8, 0.14, 0.8), "offset": (0.0, -0.05, 0.0)},
            {"kind": "box", "scale": (0.8, 0.9, 0.14), "offset": (0.0, 0.48, -0.34)},
            {"kind": "box", "scale": (0.12, 0.82, 0.12), "offset": (-0.32, 0.0, -0.28)},
            {"kind": "box", "scale": (0.12, 0.82, 0.12), "offset": (0.32, 0.0, -0.28)},
            {"kind": "box", "scale": (0.12, 0.82, 0.12), "offset": (-0.32, 0.0, 0.28)},
            {"kind": "box", "scale": (0.12, 0.82, 0.12), "offset": (0.32, 0.0, 0.28)},
        ],
    },
    "rock": {
        "family": "props",
        "label": "Rock",
        "material_slots": ["stone"],
        "parts": [
            {"kind": "pyramid", "scale": (0.95, 0.7, 0.9), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.55, 0.3, 0.45), "offset": (0.22, -0.1, -0.15)},
        ],
    },
    "save_point": {
        "family": "props",
        "label": "Save Point",
        "material_slots": ["crystal", "stone"],
        "parts": [
            {"kind": "prism", "scale": (0.42, 1.1, 0.42), "offset": (0.0, 0.32, 0.0), "sides": 6},
            {"kind": "box", "scale": (0.68, 0.14, 0.68), "offset": (0.0, -0.45, 0.0)},
        ],
    },
    "boat_marker": {
        "family": "props",
        "label": "Boat Marker",
        "material_slots": ["wood", "cloth"],
        "parts": [
            {"kind": "box", "scale": (1.0, 0.18, 0.32), "offset": (0.0, -0.18, 0.0)},
            {"kind": "pyramid", "scale": (0.65, 0.95, 0.4), "offset": (0.0, 0.42, 0.0)},
        ],
    },
    "campfire": {
        "family": "props",
        "label": "Campfire",
        "material_slots": ["wood", "stone"],
        "parts": [
            {"kind": "box", "scale": (0.95, 0.08, 0.95), "offset": (0.0, -0.42, 0.0)},
            {"kind": "box", "scale": (0.12, 0.42, 0.12), "offset": (-0.22, -0.2, -0.04)},
            {"kind": "box", "scale": (0.12, 0.42, 0.12), "offset": (0.22, -0.2, 0.04)},
            {"kind": "pyramid", "scale": (0.36, 0.44, 0.36), "offset": (0.0, -0.12, 0.0)},
        ],
    },
    "market_stall": {
        "family": "props",
        "label": "Market Stall",
        "material_slots": ["wood", "cloth"],
        "parts": [
            {"kind": "box", "scale": (1.45, 0.12, 0.9), "offset": (0.0, 0.55, 0.0)},
            {"kind": "box", "scale": (1.55, 0.18, 0.95), "offset": (0.0, 0.85, 0.0)},
            {"kind": "box", "scale": (0.14, 1.05, 0.14), "offset": (-0.6, 0.0, -0.34)},
            {"kind": "box", "scale": (0.14, 1.05, 0.14), "offset": (0.6, 0.0, -0.34)},
            {"kind": "box", "scale": (0.14, 1.05, 0.14), "offset": (-0.6, 0.0, 0.34)},
            {"kind": "box", "scale": (0.14, 1.05, 0.14), "offset": (0.6, 0.0, 0.34)},
        ],
    },
    "lantern_post": {
        "family": "props",
        "label": "Lantern Post",
        "material_slots": ["wood", "metal"],
        "parts": [
            {"kind": "pillar", "scale": (0.16, 1.7, 0.16), "offset": (0.0, 0.1, 0.0)},
            {"kind": "box", "scale": (0.65, 0.08, 0.08), "offset": (0.22, 0.82, 0.0)},
            {"kind": "box", "scale": (0.2, 0.28, 0.2), "offset": (0.46, 0.62, 0.0)},
        ],
    },
    "shrine_marker": {
        "family": "architecture",
        "label": "Shrine Marker",
        "material_slots": ["stone", "marble"],
        "parts": [
            {"kind": "pillar", "scale": (0.36, 1.45, 0.36), "offset": (0.0, 0.28, 0.0)},
            {"kind": "box", "scale": (0.85, 0.15, 0.85), "offset": (0.0, -0.52, 0.0)},
            {"kind": "prism", "scale": (0.52, 0.38, 0.52), "offset": (0.0, 1.15, 0.0), "sides": 8},
        ],
    },
    "obelisk": {
        "family": "architecture",
        "label": "Obelisk",
        "material_slots": ["stone", "marble"],
        "parts": [
            {"kind": "pyramid", "scale": (0.45, 1.8, 0.45), "offset": (0.0, 0.55, 0.0)},
            {"kind": "box", "scale": (0.65, 0.18, 0.65), "offset": (0.0, -0.6, 0.0)},
        ],
    },
    "pillar": {
        "family": "architecture",
        "label": "Pillar",
        "material_slots": ["stone"],
        "parts": [
            {"kind": "pillar", "scale": (0.45, 1.8, 0.45), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.68, 0.12, 0.68), "offset": (0.0, -0.92, 0.0)},
            {"kind": "box", "scale": (0.58, 0.1, 0.58), "offset": (0.0, 0.94, 0.0)},
        ],
    },
    "arch": {
        "family": "architecture",
        "label": "Arch",
        "material_slots": ["stone", "marble"],
        "parts": [
            {"kind": "box", "scale": (0.3, 1.5, 0.3), "offset": (-0.48, 0.0, 0.0)},
            {"kind": "box", "scale": (0.3, 1.5, 0.3), "offset": (0.48, 0.0, 0.0)},
            {"kind": "box", "scale": (1.25, 0.24, 0.32), "offset": (0.0, 0.88, 0.0)},
        ],
    },
    "wall_module": {
        "family": "architecture",
        "label": "Wall Module",
        "material_slots": ["stone"],
        "parts": [
            {"kind": "box", "scale": (1.5, 1.0, 0.28), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.18, 1.18, 0.18), "offset": (-0.6, 0.0, 0.12)},
            {"kind": "box", "scale": (0.18, 1.18, 0.18), "offset": (0.6, 0.0, 0.12)},
        ],
    },
    "crystal_altar": {
        "family": "architecture",
        "label": "Crystal Altar",
        "material_slots": ["marble", "crystal"],
        "parts": [
            {"kind": "box", "scale": (1.35, 0.2, 1.35), "offset": (0.0, -0.62, 0.0)},
            {"kind": "box", "scale": (0.72, 0.34, 0.72), "offset": (0.0, -0.34, 0.0)},
            {"kind": "prism", "scale": (0.35, 1.05, 0.35), "offset": (0.0, 0.45, 0.0), "sides": 8},
        ],
    },
    "ruin_gateway": {
        "family": "architecture",
        "label": "Ruin Gateway",
        "material_slots": ["stone", "marble"],
        "parts": [
            {"kind": "box", "scale": (0.28, 1.8, 0.32), "offset": (-0.58, 0.0, 0.0)},
            {"kind": "box", "scale": (0.28, 1.8, 0.32), "offset": (0.58, 0.0, 0.0)},
            {"kind": "box", "scale": (1.6, 0.24, 0.34), "offset": (0.0, 0.92, 0.0)},
            {"kind": "box", "scale": (1.1, 0.12, 0.28), "offset": (0.0, 0.62, 0.0)},
        ],
    },
    "fortress_bastion": {
        "family": "architecture",
        "label": "Fortress Bastion",
        "material_slots": ["stone", "metal"],
        "parts": [
            {"kind": "box", "scale": (1.45, 1.2, 1.1), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (1.55, 0.16, 1.2), "offset": (0.0, 0.72, 0.0)},
            {"kind": "box", "scale": (0.28, 0.42, 0.28), "offset": (-0.56, 1.0, -0.42)},
            {"kind": "box", "scale": (0.28, 0.42, 0.28), "offset": (0.56, 1.0, -0.42)},
            {"kind": "box", "scale": (0.28, 0.42, 0.28), "offset": (-0.56, 1.0, 0.42)},
            {"kind": "box", "scale": (0.28, 0.42, 0.28), "offset": (0.56, 1.0, 0.42)},
        ],
    },
    "tree": {
        "family": "foliage",
        "label": "Tree",
        "material_slots": ["bark", "leaf"],
        "parts": [
            {"kind": "pillar", "scale": (0.28, 1.45, 0.28), "offset": (0.0, -0.1, 0.0)},
            {"kind": "prism", "scale": (1.0, 0.92, 1.0), "offset": (0.0, 0.72, 0.0), "sides": 6},
            {"kind": "box", "scale": (0.72, 0.48, 0.72), "offset": (0.2, 1.0, -0.18)},
        ],
    },
    "bush": {
        "family": "foliage",
        "label": "Bush",
        "material_slots": ["leaf"],
        "parts": [
            {"kind": "prism", "scale": (0.68, 0.38, 0.68), "offset": (0.0, 0.0, 0.0), "sides": 6},
            {"kind": "box", "scale": (0.42, 0.26, 0.42), "offset": (0.28, 0.1, 0.1)},
            {"kind": "box", "scale": (0.42, 0.26, 0.42), "offset": (-0.18, 0.08, -0.2)},
        ],
    },
    "deadwood": {
        "family": "foliage",
        "label": "Deadwood",
        "material_slots": ["bark"],
        "parts": [
            {"kind": "pillar", "scale": (0.22, 1.2, 0.22), "offset": (0.0, -0.02, 0.0)},
            {"kind": "box", "scale": (0.82, 0.1, 0.12), "offset": (0.0, 0.42, 0.06)},
            {"kind": "box", "scale": (0.58, 0.08, 0.1), "offset": (-0.12, 0.68, -0.04)},
        ],
    },
    "sacred_shrub": {
        "family": "foliage",
        "label": "Sacred Shrub",
        "material_slots": ["leaf", "crystal"],
        "parts": [
            {"kind": "prism", "scale": (0.62, 0.34, 0.62), "offset": (0.0, 0.0, 0.0), "sides": 6},
            {"kind": "box", "scale": (0.36, 0.38, 0.36), "offset": (0.0, 0.28, 0.0)},
            {"kind": "prism", "scale": (0.18, 0.24, 0.18), "offset": (0.2, 0.42, -0.08), "sides": 8},
        ],
    },
    "potion": {
        "family": "items",
        "label": "Potion",
        "material_slots": ["glass", "crystal", "metal"],
        "parts": [
            {"kind": "prism", "scale": (0.42, 0.82, 0.42), "offset": (0.0, -0.02, 0.0), "sides": 8},
            {"kind": "box", "scale": (0.18, 0.38, 0.18), "offset": (0.0, 0.52, 0.0)},
            {"kind": "box", "scale": (0.26, 0.1, 0.26), "offset": (0.0, 0.75, 0.0)},
        ],
    },
    "sword_icon_mesh": {
        "family": "items",
        "label": "Sword Icon Mesh",
        "material_slots": ["metal", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.12, 1.15, 0.18), "offset": (0.0, 0.4, 0.0)},
            {"kind": "box", "scale": (0.42, 0.12, 0.24), "offset": (0.0, -0.1, 0.0)},
            {"kind": "box", "scale": (0.18, 0.28, 0.18), "offset": (0.0, -0.42, 0.0)},
        ],
    },
    "relic_orb": {
        "family": "items",
        "label": "Relic Orb",
        "material_slots": ["crystal", "metal"],
        "parts": [
            {"kind": "prism", "scale": (0.42, 0.42, 0.42), "offset": (0.0, 0.24, 0.0), "sides": 10},
            {"kind": "box", "scale": (0.62, 0.12, 0.62), "offset": (0.0, -0.12, 0.0)},
            {"kind": "box", "scale": (0.2, 0.3, 0.2), "offset": (0.0, -0.34, 0.0)},
        ],
    },
    "field_ration": {
        "family": "items",
        "label": "Field Ration",
        "material_slots": ["cloth", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.72, 0.42, 0.38), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.78, 0.08, 0.44), "offset": (0.0, 0.22, 0.0)},
        ],
    },
    "npc_humanoid": {
        "family": "characters_static",
        "label": "NPC Humanoid",
        "material_slots": ["cloth", "leather", "metal"],
        "parts": [
            {"kind": "box", "scale": (0.55, 0.72, 0.32), "offset": (0.0, 0.22, 0.0)},
            {"kind": "box", "scale": (0.4, 0.38, 0.4), "offset": (0.0, 0.92, 0.0)},
            {"kind": "box", "scale": (0.16, 0.72, 0.16), "offset": (-0.28, -0.35, 0.0)},
            {"kind": "box", "scale": (0.16, 0.72, 0.16), "offset": (0.28, -0.35, 0.0)},
            {"kind": "box", "scale": (0.18, 0.78, 0.18), "offset": (-0.18, -1.02, 0.0)},
            {"kind": "box", "scale": (0.18, 0.78, 0.18), "offset": (0.18, -1.02, 0.0)},
        ],
    },
    "npc_guard": {
        "family": "characters_static",
        "label": "NPC Guard",
        "material_slots": ["cloth", "metal", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.6, 0.78, 0.34), "offset": (0.0, 0.18, 0.0)},
            {"kind": "box", "scale": (0.42, 0.36, 0.42), "offset": (0.0, 0.9, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (-0.22, -0.98, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (0.22, -0.98, 0.0)},
            {"kind": "box", "scale": (0.16, 0.7, 0.16), "offset": (-0.34, -0.22, 0.0)},
            {"kind": "box", "scale": (0.16, 0.7, 0.16), "offset": (0.34, -0.22, 0.0)},
        ],
    },
    "npc_priest": {
        "family": "characters_static",
        "label": "NPC Priest",
        "material_slots": ["cloth", "crystal"],
        "parts": [
            {"kind": "box", "scale": (0.52, 0.88, 0.3), "offset": (0.0, 0.15, 0.0)},
            {"kind": "box", "scale": (0.38, 0.34, 0.38), "offset": (0.0, 0.9, 0.0)},
            {"kind": "box", "scale": (0.16, 0.74, 0.16), "offset": (-0.18, -0.98, 0.0)},
            {"kind": "box", "scale": (0.16, 0.74, 0.16), "offset": (0.18, -0.98, 0.0)},
            {"kind": "prism", "scale": (0.14, 0.3, 0.14), "offset": (0.0, 0.48, 0.24), "sides": 8},
        ],
    },
    "enemy_beast": {
        "family": "enemies_static",
        "label": "Enemy Beast",
        "material_slots": ["bone", "leather", "metal"],
        "parts": [
            {"kind": "box", "scale": (0.72, 0.52, 0.44), "offset": (0.0, 0.1, 0.0)},
            {"kind": "box", "scale": (0.44, 0.34, 0.32), "offset": (0.45, 0.22, 0.0)},
            {"kind": "box", "scale": (0.18, 0.66, 0.18), "offset": (-0.34, -0.32, -0.18)},
            {"kind": "box", "scale": (0.18, 0.66, 0.18), "offset": (-0.34, -0.32, 0.18)},
            {"kind": "prism", "scale": (0.22, 0.52, 0.22), "offset": (-0.68, 0.0, 0.0), "sides": 6},
        ],
    },
    "enemy_hunter": {
        "family": "enemies_static",
        "label": "Enemy Hunter",
        "material_slots": ["leather", "metal", "bone"],
        "parts": [
            {"kind": "box", "scale": (0.58, 0.76, 0.34), "offset": (0.0, 0.2, 0.0)},
            {"kind": "box", "scale": (0.4, 0.34, 0.4), "offset": (0.0, 0.92, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (-0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.18, 0.68, 0.18), "offset": (0.38, -0.14, 0.04)},
        ],
    },
    "enemy_sentinel": {
        "family": "enemies_static",
        "label": "Enemy Sentinel",
        "material_slots": ["stone", "metal", "crystal"],
        "parts": [
            {"kind": "box", "scale": (0.66, 1.02, 0.4), "offset": (0.0, 0.06, 0.0)},
            {"kind": "box", "scale": (0.48, 0.36, 0.48), "offset": (0.0, 0.88, 0.0)},
            {"kind": "box", "scale": (0.2, 0.76, 0.2), "offset": (-0.24, -1.02, 0.0)},
            {"kind": "box", "scale": (0.2, 0.76, 0.2), "offset": (0.24, -1.02, 0.0)},
            {"kind": "prism", "scale": (0.14, 0.34, 0.14), "offset": (0.0, 0.4, 0.3), "sides": 8},
        ],
    },
    "shop_marker": {
        "family": "props",
        "label": "Shop Marker",
        "material_slots": ["wood", "cloth"],
        "parts": [
            {"kind": "pillar", "scale": (0.16, 1.4, 0.16), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.68, 0.42, 0.08), "offset": (0.0, 0.72, 0.0)},
            {"kind": "box", "scale": (0.54, 0.18, 0.06), "offset": (0.0, 0.56, 0.0)},
        ],
    },
    "inn_marker": {
        "family": "props",
        "label": "Inn Marker",
        "material_slots": ["wood", "cloth"],
        "parts": [
            {"kind": "pillar", "scale": (0.16, 1.4, 0.16), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.62, 0.38, 0.08), "offset": (0.0, 0.72, 0.0)},
            {"kind": "prism", "scale": (0.24, 0.18, 0.24), "offset": (0.0, 0.96, 0.0), "sides": 4},
        ],
    },
    "enemy_spawn": {
        "family": "props",
        "label": "Enemy Spawn",
        "material_slots": ["stone", "bone"],
        "parts": [
            {"kind": "prism", "scale": (0.54, 0.12, 0.54), "offset": (0.0, -0.42, 0.0), "sides": 6},
            {"kind": "pyramid", "scale": (0.28, 0.36, 0.28), "offset": (-0.22, -0.2, 0.0)},
            {"kind": "pyramid", "scale": (0.28, 0.36, 0.28), "offset": (0.22, -0.2, 0.0)},
        ],
    },
    "ice_crystal": {
        "family": "props",
        "label": "Ice Crystal",
        "material_slots": ["crystal"],
        "parts": [
            {"kind": "prism", "scale": (0.28, 1.1, 0.28), "offset": (0.0, 0.1, 0.0), "sides": 6},
            {"kind": "prism", "scale": (0.18, 0.64, 0.18), "offset": (0.3, 0.2, 0.0), "sides": 6},
            {"kind": "prism", "scale": (0.14, 0.48, 0.14), "offset": (-0.24, 0.0, 0.22), "sides": 6},
        ],
    },
    "stone_tablet": {
        "family": "props",
        "label": "Stone Tablet",
        "material_slots": ["stone", "marble"],
        "parts": [
            {"kind": "box", "scale": (0.78, 1.1, 0.14), "offset": (0.0, 0.16, 0.0)},
            {"kind": "box", "scale": (0.92, 0.16, 0.24), "offset": (0.0, -0.6, 0.0)},
        ],
    },
    "signal_brazier": {
        "family": "props",
        "label": "Signal Brazier",
        "material_slots": ["metal", "stone"],
        "parts": [
            {"kind": "pillar", "scale": (0.14, 1.2, 0.14), "offset": (0.0, -0.2, 0.0)},
            {"kind": "prism", "scale": (0.52, 0.42, 0.52), "offset": (0.0, 0.56, 0.0), "sides": 8},
            {"kind": "box", "scale": (0.68, 0.1, 0.68), "offset": (0.0, 0.36, 0.0)},
        ],
    },
    "tower_top": {
        "family": "architecture",
        "label": "Tower Top",
        "material_slots": ["stone", "metal"],
        "parts": [
            {"kind": "prism", "scale": (0.82, 1.0, 0.82), "offset": (0.0, 0.0, 0.0), "sides": 8},
            {"kind": "pyramid", "scale": (0.92, 0.58, 0.92), "offset": (0.0, 0.72, 0.0)},
            {"kind": "box", "scale": (0.96, 0.14, 0.96), "offset": (0.0, -0.54, 0.0)},
        ],
    },
    "dungeon_gate": {
        "family": "architecture",
        "label": "Dungeon Gate",
        "material_slots": ["stone", "metal"],
        "parts": [
            {"kind": "box", "scale": (0.28, 1.85, 0.3), "offset": (-0.52, 0.0, 0.0)},
            {"kind": "box", "scale": (0.28, 1.85, 0.3), "offset": (0.52, 0.0, 0.0)},
            {"kind": "box", "scale": (1.42, 0.28, 0.32), "offset": (0.0, 0.96, 0.0)},
            {"kind": "box", "scale": (0.8, 1.6, 0.1), "offset": (0.0, -0.1, 0.0)},
        ],
    },
    "bridge_support": {
        "family": "architecture",
        "label": "Bridge Support",
        "material_slots": ["stone"],
        "parts": [
            {"kind": "box", "scale": (0.48, 1.4, 0.48), "offset": (0.0, -0.3, 0.0)},
            {"kind": "box", "scale": (1.5, 0.22, 0.54), "offset": (0.0, 0.52, 0.0)},
            {"kind": "box", "scale": (0.58, 0.32, 0.32), "offset": (-0.6, 0.16, 0.0)},
            {"kind": "box", "scale": (0.58, 0.32, 0.32), "offset": (0.6, 0.16, 0.0)},
        ],
    },
    "palm_tree": {
        "family": "foliage",
        "label": "Palm Tree",
        "material_slots": ["bark", "leaf"],
        "parts": [
            {"kind": "pillar", "scale": (0.22, 1.75, 0.22), "offset": (0.06, 0.0, 0.0)},
            {"kind": "box", "scale": (0.9, 0.12, 0.22), "offset": (0.0, 0.92, 0.12)},
            {"kind": "box", "scale": (0.9, 0.12, 0.22), "offset": (0.0, 0.92, -0.12)},
            {"kind": "box", "scale": (0.22, 0.12, 0.82), "offset": (0.12, 0.92, 0.0)},
        ],
    },
    "highland_shrub": {
        "family": "foliage",
        "label": "Highland Shrub",
        "material_slots": ["leaf", "bark"],
        "parts": [
            {"kind": "prism", "scale": (0.72, 0.44, 0.72), "offset": (0.0, 0.0, 0.0), "sides": 6},
            {"kind": "box", "scale": (0.38, 0.28, 0.38), "offset": (-0.26, 0.12, 0.12)},
            {"kind": "box", "scale": (0.38, 0.28, 0.38), "offset": (0.26, 0.08, -0.14)},
        ],
    },
    "cave_fungus": {
        "family": "foliage",
        "label": "Cave Fungus",
        "material_slots": ["leaf"],
        "parts": [
            {"kind": "pillar", "scale": (0.14, 0.52, 0.14), "offset": (0.0, -0.2, 0.0)},
            {"kind": "prism", "scale": (0.58, 0.18, 0.58), "offset": (0.0, 0.16, 0.0), "sides": 8},
            {"kind": "pillar", "scale": (0.1, 0.38, 0.1), "offset": (0.22, -0.26, 0.1)},
            {"kind": "prism", "scale": (0.44, 0.14, 0.44), "offset": (0.22, -0.02, 0.1), "sides": 8},
        ],
    },
    "staff_icon_mesh": {
        "family": "items",
        "label": "Staff Icon Mesh",
        "material_slots": ["wood", "crystal", "metal"],
        "parts": [
            {"kind": "pillar", "scale": (0.1, 1.5, 0.1), "offset": (0.0, 0.0, 0.0)},
            {"kind": "prism", "scale": (0.24, 0.36, 0.24), "offset": (0.0, 0.84, 0.0), "sides": 6},
            {"kind": "box", "scale": (0.38, 0.1, 0.1), "offset": (0.0, 0.72, 0.0)},
        ],
    },
    "medallion": {
        "family": "items",
        "label": "Medallion",
        "material_slots": ["metal", "crystal"],
        "parts": [
            {"kind": "prism", "scale": (0.48, 0.08, 0.48), "offset": (0.0, 0.0, 0.0), "sides": 10},
            {"kind": "prism", "scale": (0.28, 0.12, 0.28), "offset": (0.0, 0.0, 0.0), "sides": 6},
            {"kind": "box", "scale": (0.08, 0.28, 0.08), "offset": (0.0, 0.24, 0.0)},
        ],
    },
    "npc_merchant": {
        "family": "characters_static",
        "label": "NPC Merchant",
        "material_slots": ["cloth", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.6, 0.76, 0.34), "offset": (0.0, 0.18, 0.0)},
            {"kind": "box", "scale": (0.42, 0.36, 0.42), "offset": (0.0, 0.88, 0.0)},
            {"kind": "box", "scale": (0.18, 0.7, 0.18), "offset": (-0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.18, 0.7, 0.18), "offset": (0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.42, 0.32, 0.42), "offset": (0.32, 0.14, 0.18)},
        ],
    },
    "npc_elder": {
        "family": "characters_static",
        "label": "NPC Elder",
        "material_slots": ["cloth", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.5, 0.8, 0.3), "offset": (0.0, 0.1, 0.0)},
            {"kind": "box", "scale": (0.38, 0.34, 0.38), "offset": (0.0, 0.82, 0.0)},
            {"kind": "box", "scale": (0.16, 0.7, 0.16), "offset": (-0.18, -0.96, 0.0)},
            {"kind": "box", "scale": (0.16, 0.7, 0.16), "offset": (0.18, -0.96, 0.0)},
            {"kind": "pillar", "scale": (0.08, 1.1, 0.08), "offset": (0.26, -0.22, 0.0)},
        ],
    },
    "npc_rebel": {
        "family": "characters_static",
        "label": "NPC Rebel",
        "material_slots": ["leather", "cloth", "metal"],
        "parts": [
            {"kind": "box", "scale": (0.58, 0.76, 0.34), "offset": (0.0, 0.2, 0.0)},
            {"kind": "box", "scale": (0.4, 0.34, 0.4), "offset": (0.0, 0.92, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (-0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.16, 0.64, 0.16), "offset": (-0.36, -0.18, 0.04)},
        ],
    },
    "enemy_mage": {
        "family": "enemies_static",
        "label": "Enemy Mage",
        "material_slots": ["cloth", "crystal", "bone"],
        "parts": [
            {"kind": "box", "scale": (0.52, 0.88, 0.3), "offset": (0.0, 0.12, 0.0)},
            {"kind": "box", "scale": (0.38, 0.34, 0.38), "offset": (0.0, 0.88, 0.0)},
            {"kind": "box", "scale": (0.16, 0.72, 0.16), "offset": (-0.18, -0.98, 0.0)},
            {"kind": "box", "scale": (0.16, 0.72, 0.16), "offset": (0.18, -0.98, 0.0)},
            {"kind": "pillar", "scale": (0.08, 1.2, 0.08), "offset": (-0.3, -0.12, 0.0)},
            {"kind": "prism", "scale": (0.2, 0.28, 0.2), "offset": (-0.3, 0.46, 0.0), "sides": 6},
        ],
    },
    "enemy_undead": {
        "family": "enemies_static",
        "label": "Enemy Undead",
        "material_slots": ["bone", "cloth", "metal"],
        "parts": [
            {"kind": "box", "scale": (0.56, 0.72, 0.32), "offset": (0.0, 0.18, 0.0)},
            {"kind": "box", "scale": (0.4, 0.32, 0.4), "offset": (0.0, 0.86, 0.0)},
            {"kind": "box", "scale": (0.16, 0.68, 0.16), "offset": (-0.2, -0.96, 0.0)},
            {"kind": "box", "scale": (0.16, 0.68, 0.16), "offset": (0.2, -0.96, 0.0)},
            {"kind": "box", "scale": (0.14, 0.66, 0.14), "offset": (-0.32, -0.2, 0.02)},
            {"kind": "box", "scale": (0.14, 0.66, 0.14), "offset": (0.32, -0.2, 0.02)},
        ],
    },
    # ── new props ──────────────────────────────────────────────────────
    "well": {
        "family": "props",
        "label": "Well",
        "material_slots": ["stone", "wood"],
        "parts": [
            {"kind": "prism", "scale": (0.72, 0.7, 0.72), "offset": (0.0, -0.18, 0.0), "sides": 8},
            {"kind": "prism", "scale": (0.82, 0.1, 0.82), "offset": (0.0, 0.18, 0.0), "sides": 8},
            {"kind": "box", "scale": (0.14, 0.82, 0.14), "offset": (-0.38, 0.56, 0.0)},
            {"kind": "box", "scale": (0.14, 0.82, 0.14), "offset": (0.38, 0.56, 0.0)},
            {"kind": "box", "scale": (0.82, 0.12, 0.14), "offset": (0.0, 0.98, 0.0)},
        ],
    },
    "fountain": {
        "family": "props",
        "label": "Fountain",
        "material_slots": ["marble", "stone"],
        "parts": [
            {"kind": "prism", "scale": (1.2, 0.18, 1.2), "offset": (0.0, -0.44, 0.0), "sides": 8},
            {"kind": "prism", "scale": (0.82, 0.12, 0.82), "offset": (0.0, -0.26, 0.0), "sides": 8},
            {"kind": "pillar", "scale": (0.18, 0.9, 0.18), "offset": (0.0, 0.14, 0.0)},
            {"kind": "prism", "scale": (0.52, 0.14, 0.52), "offset": (0.0, 0.6, 0.0), "sides": 6},
        ],
    },
    "statue_plinth": {
        "family": "props",
        "label": "Statue Plinth",
        "material_slots": ["marble", "stone"],
        "parts": [
            {"kind": "box", "scale": (1.0, 0.22, 1.0), "offset": (0.0, -0.52, 0.0)},
            {"kind": "box", "scale": (0.88, 0.18, 0.88), "offset": (0.0, -0.28, 0.0)},
            {"kind": "box", "scale": (0.72, 1.2, 0.58), "offset": (0.0, 0.4, 0.0)},
            {"kind": "box", "scale": (0.38, 0.34, 0.38), "offset": (0.0, 1.14, 0.0)},
        ],
    },
    "sign_post": {
        "family": "props",
        "label": "Sign Post",
        "material_slots": ["wood"],
        "parts": [
            {"kind": "pillar", "scale": (0.12, 1.5, 0.12), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.72, 0.32, 0.08), "offset": (0.22, 0.62, 0.0)},
            {"kind": "box", "scale": (0.3, 0.08, 0.06), "offset": (0.06, 0.46, 0.0)},
        ],
    },
    "rubble_pile": {
        "family": "props",
        "label": "Rubble Pile",
        "material_slots": ["stone"],
        "parts": [
            {"kind": "pyramid", "scale": (1.1, 0.45, 0.9), "offset": (0.0, -0.22, 0.0)},
            {"kind": "box", "scale": (0.42, 0.26, 0.38), "offset": (-0.32, -0.1, 0.18)},
            {"kind": "box", "scale": (0.34, 0.2, 0.3), "offset": (0.3, -0.12, -0.22)},
            {"kind": "box", "scale": (0.22, 0.18, 0.24), "offset": (0.18, 0.0, 0.26)},
        ],
    },
    # ── new architecture ───────────────────────────────────────────────
    "defensive_wall": {
        "family": "architecture",
        "label": "Defensive Wall",
        "material_slots": ["stone"],
        "parts": [
            {"kind": "box", "scale": (2.0, 1.2, 0.4), "offset": (0.0, 0.0, 0.0)},
            {"kind": "box", "scale": (0.28, 0.42, 0.44), "offset": (-0.82, 0.82, 0.0)},
            {"kind": "box", "scale": (0.28, 0.42, 0.44), "offset": (0.0, 0.82, 0.0)},
            {"kind": "box", "scale": (0.28, 0.42, 0.44), "offset": (0.82, 0.82, 0.0)},
        ],
    },
    "gatehouse": {
        "family": "architecture",
        "label": "Gatehouse",
        "material_slots": ["stone", "metal"],
        "parts": [
            {"kind": "box", "scale": (0.52, 2.0, 0.62), "offset": (-0.78, 0.0, 0.0)},
            {"kind": "box", "scale": (0.52, 2.0, 0.62), "offset": (0.78, 0.0, 0.0)},
            {"kind": "box", "scale": (2.2, 0.36, 0.68), "offset": (0.0, 1.08, 0.0)},
            {"kind": "box", "scale": (0.9, 1.8, 0.14), "offset": (0.0, -0.1, 0.0)},
            {"kind": "pyramid", "scale": (0.62, 0.5, 0.68), "offset": (-0.78, 1.38, 0.0)},
            {"kind": "pyramid", "scale": (0.62, 0.5, 0.68), "offset": (0.78, 1.38, 0.0)},
        ],
    },
    "watchtower": {
        "family": "architecture",
        "label": "Watchtower",
        "material_slots": ["stone", "wood"],
        "parts": [
            {"kind": "prism", "scale": (0.78, 2.2, 0.78), "offset": (0.0, -0.1, 0.0), "sides": 8},
            {"kind": "prism", "scale": (0.96, 0.22, 0.96), "offset": (0.0, 1.2, 0.0), "sides": 8},
            {"kind": "pyramid", "scale": (1.04, 0.72, 1.04), "offset": (0.0, 1.56, 0.0)},
        ],
    },
    "market_arch": {
        "family": "architecture",
        "label": "Market Arch",
        "material_slots": ["stone", "marble"],
        "parts": [
            {"kind": "box", "scale": (0.32, 1.65, 0.44), "offset": (-0.64, 0.0, 0.0)},
            {"kind": "box", "scale": (0.32, 1.65, 0.44), "offset": (0.64, 0.0, 0.0)},
            {"kind": "prism", "scale": (1.72, 0.36, 0.48), "offset": (0.0, 0.94, 0.0), "sides": 4},
            {"kind": "box", "scale": (0.26, 0.18, 0.46), "offset": (-0.22, -0.52, 0.0)},
            {"kind": "box", "scale": (0.26, 0.18, 0.46), "offset": (0.22, -0.52, 0.0)},
        ],
    },
    "temple_steps": {
        "family": "architecture",
        "label": "Temple Steps",
        "material_slots": ["marble", "stone"],
        "parts": [
            {"kind": "box", "scale": (2.0, 0.2, 0.5), "offset": (0.0, -0.6, 0.7)},
            {"kind": "box", "scale": (1.8, 0.2, 0.5), "offset": (0.0, -0.4, 0.42)},
            {"kind": "box", "scale": (1.6, 0.2, 0.5), "offset": (0.0, -0.2, 0.14)},
            {"kind": "box", "scale": (1.4, 0.2, 0.5), "offset": (0.0, 0.0, -0.14)},
        ],
    },
    # ── new foliage ────────────────────────────────────────────────────
    "snow_pine": {
        "family": "foliage",
        "label": "Snow Pine",
        "material_slots": ["bark", "leaf"],
        "parts": [
            {"kind": "pillar", "scale": (0.22, 1.55, 0.22), "offset": (0.0, -0.08, 0.0)},
            {"kind": "prism", "scale": (0.92, 0.44, 0.92), "offset": (0.0, 0.32, 0.0), "sides": 6},
            {"kind": "prism", "scale": (0.72, 0.38, 0.72), "offset": (0.0, 0.66, 0.0), "sides": 6},
            {"kind": "prism", "scale": (0.48, 0.32, 0.48), "offset": (0.0, 0.96, 0.0), "sides": 6},
        ],
    },
    "marsh_reed": {
        "family": "foliage",
        "label": "Marsh Reed",
        "material_slots": ["leaf"],
        "parts": [
            {"kind": "pillar", "scale": (0.08, 1.2, 0.08), "offset": (-0.18, -0.06, 0.1)},
            {"kind": "pillar", "scale": (0.08, 1.4, 0.08), "offset": (0.04, 0.0, -0.08)},
            {"kind": "pillar", "scale": (0.08, 1.1, 0.08), "offset": (0.2, -0.1, 0.06)},
            {"kind": "box", "scale": (0.06, 0.28, 0.06), "offset": (-0.18, 0.66, 0.1)},
            {"kind": "box", "scale": (0.06, 0.28, 0.06), "offset": (0.04, 0.76, -0.08)},
        ],
    },
    "ancient_fern": {
        "family": "foliage",
        "label": "Ancient Fern",
        "material_slots": ["leaf"],
        "parts": [
            {"kind": "pillar", "scale": (0.12, 0.6, 0.12), "offset": (0.0, -0.2, 0.0)},
            {"kind": "box", "scale": (0.82, 0.06, 0.18), "offset": (0.0, 0.14, 0.0)},
            {"kind": "box", "scale": (0.68, 0.06, 0.16), "offset": (0.0, 0.24, 0.12)},
            {"kind": "box", "scale": (0.58, 0.06, 0.14), "offset": (0.0, 0.32, -0.1)},
        ],
    },
    "volcanic_rock_cluster": {
        "family": "foliage",
        "label": "Volcanic Rock Cluster",
        "material_slots": ["stone"],
        "parts": [
            {"kind": "pyramid", "scale": (0.82, 0.65, 0.74), "offset": (0.0, -0.2, 0.0)},
            {"kind": "pyramid", "scale": (0.52, 0.48, 0.48), "offset": (-0.44, -0.28, 0.2)},
            {"kind": "pyramid", "scale": (0.38, 0.36, 0.34), "offset": (0.38, -0.3, -0.22)},
        ],
    },
    "coral_formation": {
        "family": "foliage",
        "label": "Coral Formation",
        "material_slots": ["crystal", "stone"],
        "parts": [
            {"kind": "prism", "scale": (0.2, 0.82, 0.2), "offset": (0.0, 0.0, 0.0), "sides": 6},
            {"kind": "prism", "scale": (0.14, 0.58, 0.14), "offset": (-0.22, -0.1, 0.14), "sides": 6},
            {"kind": "prism", "scale": (0.14, 0.66, 0.14), "offset": (0.2, -0.06, -0.16), "sides": 6},
            {"kind": "prism", "scale": (0.1, 0.44, 0.1), "offset": (0.1, 0.08, 0.24), "sides": 6},
        ],
    },
    # ── new items ──────────────────────────────────────────────────────
    "shield_icon_mesh": {
        "family": "items",
        "label": "Shield Icon Mesh",
        "material_slots": ["metal", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.82, 0.98, 0.12), "offset": (0.0, 0.0, 0.0)},
            {"kind": "prism", "scale": (0.64, 0.22, 0.14), "offset": (0.0, -0.52, 0.0), "sides": 4},
            {"kind": "box", "scale": (0.72, 0.08, 0.1), "offset": (0.0, 0.46, 0.0)},
        ],
    },
    "armor_icon_mesh": {
        "family": "items",
        "label": "Armor Icon Mesh",
        "material_slots": ["metal", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.7, 0.56, 0.28), "offset": (0.0, 0.14, 0.0)},
            {"kind": "box", "scale": (0.18, 0.36, 0.22), "offset": (-0.42, 0.28, 0.0)},
            {"kind": "box", "scale": (0.18, 0.36, 0.22), "offset": (0.42, 0.28, 0.0)},
            {"kind": "box", "scale": (0.52, 0.22, 0.24), "offset": (0.0, -0.26, 0.0)},
        ],
    },
    "ring_icon_mesh": {
        "family": "items",
        "label": "Ring Icon Mesh",
        "material_slots": ["metal", "crystal"],
        "parts": [
            {"kind": "prism", "scale": (0.38, 0.1, 0.38), "offset": (0.0, 0.0, 0.0), "sides": 10},
            {"kind": "prism", "scale": (0.28, 0.08, 0.28), "offset": (0.0, 0.0, 0.0), "sides": 10},
            {"kind": "prism", "scale": (0.12, 0.14, 0.12), "offset": (0.0, 0.0, 0.2), "sides": 6},
        ],
    },
    "gem_icon_mesh": {
        "family": "items",
        "label": "Gem Icon Mesh",
        "material_slots": ["crystal"],
        "parts": [
            {"kind": "prism", "scale": (0.42, 0.22, 0.42), "offset": (0.0, 0.06, 0.0), "sides": 8},
            {"kind": "pyramid", "scale": (0.42, 0.3, 0.42), "offset": (0.0, -0.12, 0.0)},
        ],
    },
    "bow_icon_mesh": {
        "family": "items",
        "label": "Bow Icon Mesh",
        "material_slots": ["wood", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.1, 1.3, 0.08), "offset": (-0.3, 0.0, 0.0)},
            {"kind": "box", "scale": (0.06, 0.9, 0.06), "offset": (0.06, 0.0, 0.0)},
            {"kind": "box", "scale": (0.48, 0.08, 0.06), "offset": (-0.12, 0.58, 0.0)},
            {"kind": "box", "scale": (0.48, 0.08, 0.06), "offset": (-0.12, -0.58, 0.0)},
        ],
    },
    # ── new characters_static ──────────────────────────────────────────
    "npc_knight": {
        "family": "characters_static",
        "label": "NPC Knight",
        "material_slots": ["metal", "cloth", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.64, 0.82, 0.36), "offset": (0.0, 0.16, 0.0)},
            {"kind": "box", "scale": (0.44, 0.38, 0.44), "offset": (0.0, 0.94, 0.0)},
            {"kind": "box", "scale": (0.2, 0.76, 0.2), "offset": (-0.22, -1.0, 0.0)},
            {"kind": "box", "scale": (0.2, 0.76, 0.2), "offset": (0.22, -1.0, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (-0.38, -0.18, 0.02)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (0.38, -0.18, 0.02)},
            {"kind": "box", "scale": (0.62, 0.08, 0.68), "offset": (0.0, 0.62, 0.0)},
        ],
    },
    "npc_sage": {
        "family": "characters_static",
        "label": "NPC Sage",
        "material_slots": ["cloth", "crystal", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.54, 0.9, 0.32), "offset": (0.0, 0.12, 0.0)},
            {"kind": "box", "scale": (0.38, 0.34, 0.38), "offset": (0.0, 0.86, 0.0)},
            {"kind": "box", "scale": (0.16, 0.72, 0.16), "offset": (-0.18, -0.98, 0.0)},
            {"kind": "box", "scale": (0.16, 0.72, 0.16), "offset": (0.18, -0.98, 0.0)},
            {"kind": "pillar", "scale": (0.08, 1.2, 0.08), "offset": (0.28, -0.18, 0.0)},
            {"kind": "prism", "scale": (0.18, 0.28, 0.18), "offset": (0.28, 0.48, 0.0), "sides": 6},
        ],
    },
    "npc_innkeeper": {
        "family": "characters_static",
        "label": "NPC Innkeeper",
        "material_slots": ["cloth", "leather"],
        "parts": [
            {"kind": "box", "scale": (0.66, 0.8, 0.38), "offset": (0.0, 0.14, 0.0)},
            {"kind": "box", "scale": (0.44, 0.36, 0.44), "offset": (0.0, 0.9, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (-0.24, -0.98, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (0.24, -0.98, 0.0)},
            {"kind": "box", "scale": (0.64, 0.22, 0.1), "offset": (0.0, 0.32, 0.2)},
        ],
    },
    "npc_blacksmith": {
        "family": "characters_static",
        "label": "NPC Blacksmith",
        "material_slots": ["leather", "metal", "cloth"],
        "parts": [
            {"kind": "box", "scale": (0.7, 0.84, 0.42), "offset": (0.0, 0.12, 0.0)},
            {"kind": "box", "scale": (0.46, 0.38, 0.46), "offset": (0.0, 0.9, 0.0)},
            {"kind": "box", "scale": (0.2, 0.76, 0.2), "offset": (-0.26, -0.98, 0.0)},
            {"kind": "box", "scale": (0.2, 0.76, 0.2), "offset": (0.26, -0.98, 0.0)},
            {"kind": "box", "scale": (0.24, 0.72, 0.22), "offset": (-0.44, -0.16, 0.0)},
            {"kind": "box", "scale": (0.22, 0.14, 0.22), "offset": (-0.44, 0.28, 0.1)},
        ],
    },
    "npc_mage_static": {
        "family": "characters_static",
        "label": "NPC Mage Static",
        "material_slots": ["cloth", "crystal", "metal"],
        "parts": [
            {"kind": "box", "scale": (0.5, 0.86, 0.3), "offset": (0.0, 0.14, 0.0)},
            {"kind": "box", "scale": (0.36, 0.32, 0.36), "offset": (0.0, 0.9, 0.0)},
            {"kind": "box", "scale": (0.14, 0.72, 0.14), "offset": (-0.18, -0.96, 0.0)},
            {"kind": "box", "scale": (0.14, 0.72, 0.14), "offset": (0.18, -0.96, 0.0)},
            {"kind": "pillar", "scale": (0.08, 1.38, 0.08), "offset": (-0.28, -0.08, 0.0)},
            {"kind": "prism", "scale": (0.22, 0.32, 0.22), "offset": (-0.28, 0.58, 0.0), "sides": 8},
        ],
    },
    "npc_thief": {
        "family": "characters_static",
        "label": "NPC Thief",
        "material_slots": ["leather", "cloth"],
        "parts": [
            {"kind": "box", "scale": (0.54, 0.74, 0.3), "offset": (0.0, 0.2, 0.0)},
            {"kind": "box", "scale": (0.36, 0.32, 0.36), "offset": (0.0, 0.9, 0.0)},
            {"kind": "box", "scale": (0.14, 0.7, 0.14), "offset": (-0.18, -0.96, 0.0)},
            {"kind": "box", "scale": (0.14, 0.7, 0.14), "offset": (0.18, -0.96, 0.0)},
            {"kind": "box", "scale": (0.14, 0.66, 0.14), "offset": (-0.3, -0.18, 0.04)},
            {"kind": "box", "scale": (0.14, 0.66, 0.14), "offset": (0.3, -0.18, 0.04)},
        ],
    },
    # ── new enemies_static ─────────────────────────────────────────────
    "enemy_golem": {
        "family": "enemies_static",
        "label": "Enemy Golem",
        "material_slots": ["stone", "metal", "crystal"],
        "parts": [
            {"kind": "box", "scale": (0.82, 0.88, 0.56), "offset": (0.0, 0.06, 0.0)},
            {"kind": "box", "scale": (0.6, 0.48, 0.6), "offset": (0.0, 0.98, 0.0)},
            {"kind": "box", "scale": (0.26, 0.82, 0.26), "offset": (-0.44, -1.08, 0.0)},
            {"kind": "box", "scale": (0.26, 0.82, 0.26), "offset": (0.44, -1.08, 0.0)},
            {"kind": "box", "scale": (0.3, 0.82, 0.3), "offset": (-0.58, -0.14, 0.0)},
            {"kind": "box", "scale": (0.3, 0.82, 0.3), "offset": (0.58, -0.14, 0.0)},
        ],
    },
    "enemy_elemental": {
        "family": "enemies_static",
        "label": "Enemy Elemental",
        "material_slots": ["crystal", "bone", "metal"],
        "parts": [
            {"kind": "prism", "scale": (0.62, 1.1, 0.62), "offset": (0.0, 0.0, 0.0), "sides": 6},
            {"kind": "prism", "scale": (0.38, 0.38, 0.38), "offset": (0.0, 0.88, 0.0), "sides": 8},
            {"kind": "prism", "scale": (0.18, 0.62, 0.18), "offset": (-0.34, -0.24, 0.12), "sides": 6},
            {"kind": "prism", "scale": (0.18, 0.62, 0.18), "offset": (0.34, -0.24, -0.12), "sides": 6},
        ],
    },
    "enemy_fiend": {
        "family": "enemies_static",
        "label": "Enemy Fiend",
        "material_slots": ["bone", "leather", "crystal"],
        "parts": [
            {"kind": "box", "scale": (0.62, 0.78, 0.38), "offset": (0.0, 0.14, 0.0)},
            {"kind": "box", "scale": (0.42, 0.36, 0.42), "offset": (0.0, 0.88, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (-0.22, -0.98, 0.0)},
            {"kind": "box", "scale": (0.18, 0.72, 0.18), "offset": (0.22, -0.98, 0.0)},
            {"kind": "pyramid", "scale": (0.28, 0.48, 0.14), "offset": (-0.42, 0.68, -0.22)},
            {"kind": "pyramid", "scale": (0.28, 0.48, 0.14), "offset": (0.42, 0.68, -0.22)},
        ],
    },
    "enemy_dragon_static": {
        "family": "enemies_static",
        "label": "Enemy Dragon Static",
        "material_slots": ["bone", "metal", "leather"],
        "parts": [
            {"kind": "box", "scale": (1.0, 0.62, 0.6), "offset": (0.0, 0.04, 0.0)},
            {"kind": "box", "scale": (0.5, 0.46, 0.48), "offset": (0.62, 0.16, 0.0)},
            {"kind": "box", "scale": (0.24, 0.72, 0.24), "offset": (-0.42, -0.54, -0.22)},
            {"kind": "box", "scale": (0.24, 0.72, 0.24), "offset": (-0.42, -0.54, 0.22)},
            {"kind": "box", "scale": (0.24, 0.72, 0.24), "offset": (0.28, -0.54, -0.22)},
            {"kind": "box", "scale": (0.24, 0.72, 0.24), "offset": (0.28, -0.54, 0.22)},
            {"kind": "prism", "scale": (0.68, 0.18, 0.68), "offset": (-0.6, 0.12, 0.0), "sides": 4},
        ],
    },
    "enemy_revenant": {
        "family": "enemies_static",
        "label": "Enemy Revenant",
        "material_slots": ["bone", "crystal", "cloth"],
        "parts": [
            {"kind": "box", "scale": (0.58, 0.78, 0.34), "offset": (0.0, 0.16, 0.0)},
            {"kind": "box", "scale": (0.42, 0.34, 0.42), "offset": (0.0, 0.88, 0.0)},
            {"kind": "box", "scale": (0.16, 0.74, 0.16), "offset": (-0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.16, 0.74, 0.16), "offset": (0.2, -0.98, 0.0)},
            {"kind": "box", "scale": (0.14, 0.7, 0.14), "offset": (-0.34, -0.16, 0.0)},
            {"kind": "box", "scale": (0.14, 0.7, 0.14), "offset": (0.34, -0.16, 0.0)},
            {"kind": "prism", "scale": (0.12, 0.3, 0.12), "offset": (0.0, 0.44, 0.26), "sides": 6},
        ],
    },
    "enemy_serpent": {
        "family": "enemies_static",
        "label": "Enemy Serpent",
        "material_slots": ["leather", "bone"],
        "parts": [
            {"kind": "prism", "scale": (0.36, 1.6, 0.36), "offset": (0.0, -0.1, 0.0), "sides": 8},
            {"kind": "prism", "scale": (0.28, 0.62, 0.28), "offset": (0.22, 0.72, 0.22), "sides": 6},
            {"kind": "box", "scale": (0.52, 0.24, 0.28), "offset": (0.36, 1.08, 0.36)},
            {"kind": "pyramid", "scale": (0.22, 0.32, 0.28), "offset": (0.64, 1.04, 0.44)},
        ],
    },
}

_MESH_FAMILY_KEYWORDS = {
    "characters_static": {
        "character",
        "npc",
        "hero",
        "knight",
        "mage",
        "rogue",
        "cleric",
        "villager",
        "sage",
        "innkeeper",
        "blacksmith",
        "thief",
    },
    "enemies_static": {
        "enemy",
        "beast",
        "undead",
        "monster",
        "fiend",
        "wolf",
        "dragon",
        "goblin",
        "golem",
        "elemental",
        "revenant",
        "serpent",
    },
    "foliage": {"tree", "bush", "leaf", "forest", "plant", "fern", "reed", "coral", "pine"},
    "architecture": {
        "pillar",
        "arch",
        "wall",
        "castle",
        "temple",
        "shrine",
        "building",
        "roof",
        "gatehouse",
        "watchtower",
        "fortress",
    },
    "items": {"potion", "sword", "blade", "icon", "gem", "relic", "artifact", "shield", "armor", "bow", "ring"},
}

_VARIANT_KEYWORDS = {
    "chest": {"chest", "treasure", "loot", "coffer"},
    "crate": {"crate", "box", "package"},
    "barrel": {"barrel", "cask", "keg"},
    "table": {"table", "desk", "dining"},
    "chair": {"chair", "seat", "stool"},
    "rock": {"rock", "stone", "boulder"},
    "save_point": {"save", "crystal", "checkpoint"},
    "boat_marker": {"boat", "ship", "harbor", "dock"},
    "campfire": {"campfire", "camp", "firepit"},
    "market_stall": {"stall", "market", "vendor"},
    "lantern_post": {"lantern", "lamp", "post"},
    "shop_marker": {"shop", "store", "merchant", "sign"},
    "inn_marker": {"inn", "lodge", "tavern"},
    "enemy_spawn": {"spawn", "lair", "horde"},
    "ice_crystal": {"ice", "crystal", "frost", "shard"},
    "stone_tablet": {"tablet", "inscription", "rune", "stone"},
    "signal_brazier": {"brazier", "signal", "beacon"},
    "shrine_marker": {"shrine", "altar", "sanctum"},
    "obelisk": {"obelisk", "spike"},
    "crystal_altar": {"crystal", "altar", "relic"},
    "ruin_gateway": {"gateway", "gate", "ruin"},
    "fortress_bastion": {"fortress", "bastion", "tower"},
    "pillar": {"pillar", "column"},
    "arch": {"arch", "gateway"},
    "wall_module": {"wall", "module", "panel"},
    "tower_top": {"tower", "parapet", "battlement"},
    "dungeon_gate": {"dungeon", "sealed", "iron", "gate"},
    "bridge_support": {"bridge", "support", "span"},
    "tree": {"tree", "forest", "oak", "pine"},
    "bush": {"bush", "shrub"},
    "deadwood": {"deadwood", "stump", "withered"},
    "sacred_shrub": {"sacred", "shrub", "blessed"},
    "palm_tree": {"palm", "tropical"},
    "highland_shrub": {"highland", "heather", "moorland"},
    "cave_fungus": {"fungus", "mushroom", "cave", "plant"},
    "potion": {"potion", "vial", "flask"},
    "sword_icon_mesh": {"sword", "blade", "weapon"},
    "relic_orb": {"orb", "relic", "artifact"},
    "field_ration": {"ration", "pack", "supply"},
    "staff_icon_mesh": {"staff", "scepter", "wand"},
    "medallion": {"medallion", "amulet", "emblem"},
    "npc_humanoid": {"npc", "human", "humanoid"},
    "npc_guard": {"guard", "soldier", "watch"},
    "npc_priest": {"priest", "cleric", "acolyte"},
    "npc_merchant": {"merchant", "trader", "shopkeeper"},
    "npc_elder": {"elder", "sage", "village", "chief"},
    "npc_rebel": {"rebel", "scout", "resistance"},
    "npc_knight": {"knight", "paladin", "cavalier"},
    "npc_sage": {"sage", "scholar", "mystic"},
    "npc_innkeeper": {"innkeeper", "barkeep", "host"},
    "npc_blacksmith": {"blacksmith", "smith", "forger"},
    "npc_mage_static": {"mage", "wizard", "sorcerer", "arcanist"},
    "npc_thief": {"thief", "rogue", "bandit"},
    "enemy_beast": {"enemy", "beast", "wolf", "monster"},
    "enemy_hunter": {"hunter", "raider", "assassin"},
    "enemy_sentinel": {"sentinel", "construct", "warden"},
    "enemy_mage": {"mage", "sorcerer", "warlock"},
    "enemy_undead": {"undead", "skeleton", "zombie"},
    "enemy_golem": {"golem", "construct", "automaton"},
    "enemy_elemental": {"elemental", "spirit", "djinn"},
    "enemy_fiend": {"fiend", "demon", "shade"},
    "enemy_dragon_static": {"dragon", "wyrm", "wyvern"},
    "enemy_revenant": {"revenant", "wraith", "phantom"},
    "enemy_serpent": {"serpent", "snake", "basilisk"},
    "well": {"well", "water_source", "cistern"},
    "fountain": {"fountain", "basin", "pool"},
    "statue_plinth": {"statue", "monument", "pedestal"},
    "sign_post": {"sign", "marker", "waypost"},
    "rubble_pile": {"rubble", "debris", "wreckage"},
    "defensive_wall": {"defensive", "rampart", "battlement_wall"},
    "gatehouse": {"gatehouse", "entrance_gate", "fortified_entry"},
    "watchtower": {"watchtower", "lookout", "observation_tower"},
    "market_arch": {"market_arch", "arcade", "bazaar_arch"},
    "temple_steps": {"temple_steps", "sacred_stairway", "ritual_steps"},
    "snow_pine": {"snow_pine", "fir", "conifer"},
    "marsh_reed": {"reed", "marsh", "wetland", "sedge"},
    "ancient_fern": {"fern", "frond", "ancient_plant"},
    "volcanic_rock_cluster": {"volcanic_rock", "obsidian_cluster", "lava_rock"},
    "coral_formation": {"coral", "reef", "sea_plant"},
    "shield_icon_mesh": {"shield", "buckler", "aegis"},
    "armor_icon_mesh": {"armor", "plate", "chestpiece"},
    "ring_icon_mesh": {"ring", "band", "circlet"},
    "gem_icon_mesh": {"gem", "jewel", "ruby", "sapphire"},
    "bow_icon_mesh": {"bow", "longbow", "crossbow"},
}


def resolve_mesh_family(tokens: list[str]) -> str:
    token_set = set(tokens)
    for family in MESH_FAMILY_ORDER:
        if token_set.intersection(_MESH_FAMILY_KEYWORDS.get(family, set())):
            return family
    return "props"


def resolve_mesh_variant(family: str, tokens: list[str]) -> str:
    token_set = set(tokens)
    for variant, keywords in _VARIANT_KEYWORDS.items():
        spec = MESH_VARIANT_SPECS[variant]
        if spec["family"] == family and token_set.intersection(keywords):
            return variant
    default_variant = MESH_FAMILY_SPECS[family]["default_variant"]
    return default_variant
