from __future__ import annotations

GAME_REWRITTEN_BUNDLE_RECIPE = {
    "name": "full_static",
    "style_profile": "ps2_ff7_ff12_highest_quality_ps2",
    "required_packs": [
        "material_pack",
        "biome_pack",
        "tileset_pack",
        "prop_pack",
        "architecture_pack",
        "foliage_pack",
        "item_pack",
        "decal_pack",
        "ui_icon_pack",
        "ui_panel_pack",
        "ui_portrait_pack",
        "character_static_pack",
        "enemy_static_pack",
    ],
    "content_targets": {
        "materials": "Content/Materials",
        "terrain": "Content/Textures",
        "tilesets": "Content/World",
        "props": "Content/Models",
        "architecture": "Content/Models",
        "foliage": "Content/Models",
        "items": "Content/Models",
        "decals": "Content/Textures",
        "ui_icons": "Content/UI",
        "ui_panels": "Content/UI",
        "ui_portraits": "Content/UI",
        "characters_static": "Content/Models",
        "enemies_static": "Content/Models",
        "bundles": "Content/Bundles",
    },
    "prompts": {
        "materials": [
            "ps2 jrpg wet stone",
            "ps2 jrpg ancient brick",
            "ps2 jrpg sacred temple marble",
            "ps2 jrpg corrupted ruin basalt",
            "ps2 jrpg imperial fortress steel",
            "ps2 jrpg rebel outpost wood",
            "ps2 jrpg royal palace gold trim marble",
            "ps2 jrpg highland granite moss",
            "ps2 jrpg coastal driftwood weathered",
            "ps2 jrpg volcanic obsidian scorched",
            "ps2 jrpg crystal shrine glowing mythril",
            "ps2 jrpg wasteland cracked clay",
        ],
        "terrain": [
            "ps2 jrpg forest ground",
            "ps2 jrpg desert ground",
            "ps2 jrpg coastal cliff path",
            "ps2 jrpg highland moss path",
            "ps2 jrpg volcanic ash road",
            "ps2 jrpg crystal shrine floor",
            "ps2 jrpg overworld grass plain",
            "ps2 jrpg sacred ruin stone floor",
            "ps2 jrpg imperial city cobblestone",
            "ps2 jrpg dungeon carved rock floor",
            "ps2 jrpg snowfield icy tundra path",
            "ps2 jrpg port dock wooden planks",
        ],
        "tilesets": [
            "ps2 jrpg overworld tileset",
            "ps2 jrpg dungeon tileset",
            "ps2 jrpg imperial city tileset",
            "ps2 jrpg port town tileset",
            "ps2 jrpg sacred ruins tileset",
            "ps2 jrpg volcanic wasteland tileset",
            "ps2 jrpg highland snowfield tileset",
            "ps2 jrpg forest wilderness tileset",
            "ps2 jrpg rebel camp tileset",
            "ps2 jrpg royal palace interior tileset",
            "ps2 jrpg coastal harbor tileset",
            "ps2 jrpg crystal sanctum tileset",
        ],
        "props": [
            "ps2 jrpg treasure chest",
            "ps2 jrpg merchant crate",
            "ps2 jrpg shrine save crystal pedestal",
            "ps2 jrpg rebel camp supply barrel",
            "ps2 jrpg imperial outpost signal brazier",
            "ps2 jrpg ancient ruin stone tablet",
            "ps2 jrpg port harbor mooring post",
            "ps2 jrpg royal banquet table",
            "ps2 jrpg highland campfire stones",
            "ps2 jrpg dungeon iron torch sconce",
            "ps2 jrpg market lantern post",
            "ps2 jrpg corrupted ruin altar fragment",
        ],
        "architecture": [
            "ps2 jrpg stone pillar",
            "ps2 jrpg temple arch",
            "ps2 jrpg imperial gate wall module",
            "ps2 jrpg port city bridge support",
            "ps2 jrpg sacred sanctum altar frame",
            "ps2 jrpg ancient ruin obelisk",
            "ps2 jrpg royal palace ornate column",
            "ps2 jrpg fortress tower bastion",
            "ps2 jrpg highland stone wall section",
            "ps2 jrpg rebel bunker entrance frame",
            "ps2 jrpg crystal shrine gateway",
            "ps2 jrpg dungeon sealed ruin gateway",
        ],
        "foliage": [
            "ps2 jrpg forest tree",
            "ps2 jrpg bush",
            "ps2 jrpg highland cedar tree",
            "ps2 jrpg coastal palm tree",
            "ps2 jrpg sacred grove crystal shrub",
            "ps2 jrpg volcanic deadwood brush",
            "ps2 jrpg overworld meadow flower cluster",
            "ps2 jrpg swamp gnarled tree",
            "ps2 jrpg ruins overgrown ivy bush",
            "ps2 jrpg snowfield frost fern",
            "ps2 jrpg desert scrub cactus",
            "ps2 jrpg dungeon cave fungus cluster",
        ],
        "items": [
            "ps2 jrpg potion",
            "ps2 jrpg sword",
            "ps2 jrpg phoenix relic token",
            "ps2 jrpg crystal charm",
            "ps2 jrpg imperial insignia",
            "ps2 jrpg rebel field kit",
            "ps2 jrpg ancient summon relic orb",
            "ps2 jrpg holy staff icon mesh",
            "ps2 jrpg dark blade corrupted relic",
            "ps2 jrpg highland ranger bow",
            "ps2 jrpg port trade cargo pouch",
            "ps2 jrpg royal crest medallion",
        ],
        "decals": [
            "ps2 jrpg rune decal",
            "ps2 jrpg sign decal",
            "ps2 jrpg sacred crest emblem",
            "ps2 jrpg corrupted sigil mark",
            "ps2 jrpg imperial banner insignia",
            "ps2 jrpg rebel resistance glyph",
            "ps2 jrpg ancient civilization floor rune",
            "ps2 jrpg royal coat of arms",
            "ps2 jrpg crystal shrine deity crest",
            "ps2 jrpg dungeon warning skull mark",
            "ps2 jrpg port cargo stamp brand",
            "ps2 jrpg wasteland scavenger territory mark",
        ],
        "ui_icons": [
            "ps2 jrpg quest icon",
            "ps2 jrpg shop icon",
            "ps2 jrpg save crystal icon",
            "ps2 jrpg summon relic icon",
            "ps2 jrpg imperial faction icon",
            "ps2 jrpg rebel faction icon",
            "ps2 jrpg world map region marker icon",
            "ps2 jrpg battle status effect icon",
            "ps2 jrpg equipment slot icon",
            "ps2 jrpg key item relic icon",
            "ps2 jrpg sacred shrine blessing icon",
            "ps2 jrpg corrupted zone warning icon",
        ],
        "ui_panels": [
            "ps2 jrpg inventory panel",
            "ps2 jrpg dialog box",
            "ps2 jrpg world map panel",
            "ps2 jrpg quest log frame",
            "ps2 jrpg imperial command hud",
            "ps2 jrpg rebel camp hud",
            "ps2 jrpg character status panel",
            "ps2 jrpg battle command menu",
            "ps2 jrpg region travel select panel",
            "ps2 jrpg shop trade interface panel",
            "ps2 jrpg sacred shrine blessing menu",
            "ps2 jrpg summon call interface panel",
        ],
        "ui_portraits": [
            "ps2 jrpg hero portrait",
            "ps2 jrpg knight portrait",
            "ps2 jrpg mage portrait",
            "ps2 jrpg rogue portrait",
            "ps2 jrpg imperial captain portrait",
            "ps2 jrpg rebel leader portrait",
            "ps2 jrpg shrine oracle portrait",
            "ps2 jrpg merchant elder portrait",
            "ps2 jrpg corrupted villain portrait",
            "ps2 jrpg highland clan chief portrait",
            "ps2 jrpg port navigator portrait",
            "ps2 jrpg royal advisor portrait",
        ],
        "characters_static": [
            "ps2 jrpg npc humanoid",
            "ps2 jrpg merchant npc",
            "ps2 jrpg imperial guard npc",
            "ps2 jrpg rebel scout npc",
            "ps2 jrpg shrine priest npc",
            "ps2 jrpg port town villager npc",
            "ps2 jrpg highland ranger npc",
            "ps2 jrpg royal court advisor npc",
            "ps2 jrpg ruins archaeologist npc",
            "ps2 jrpg corrupted cultist npc",
            "ps2 jrpg inn keeper npc",
            "ps2 jrpg elder village chief npc",
        ],
        "enemies_static": [
            "ps2 jrpg wolf enemy",
            "ps2 jrpg beast enemy",
            "ps2 jrpg corrupted ruin fiend enemy",
            "ps2 jrpg imperial war hound enemy",
            "ps2 jrpg volcanic drake enemy",
            "ps2 jrpg undead temple sentinel enemy",
            "ps2 jrpg highland mountain troll enemy",
            "ps2 jrpg coastal sea serpent enemy",
            "ps2 jrpg wasteland bandit raider enemy",
            "ps2 jrpg corrupted mage construct enemy",
            "ps2 jrpg dungeon golem sentinel enemy",
            "ps2 jrpg sacred grove corrupted spirit enemy",
        ],
    },
}
