from __future__ import annotations

GAME_REWRITTEN_BUNDLE_RECIPE = {
    "name": "full_static",
    "style_profile": "ps2_ff7_ff12_highest_quality_ps2",
    "required_packs": [
        "material_pack",
        "biome_pack",
        "tileset_pack",
        "prop_pack",
        "architecture_pack",
        "foliage_pack",
        "item_pack",
        "decal_pack",
        "ui_icon_pack",
        "ui_panel_pack",
        "ui_portrait_pack",
        "character_static_pack",
        "enemy_static_pack",
    ],
    "content_targets": {
        "materials": "Content/Materials",
        "terrain": "Content/Textures",
        "tilesets": "Content/World",
        "props": "Content/Models",
        "architecture": "Content/Models",
        "foliage": "Content/Models",
        "items": "Content/Models",
        "decal": "Content/Textures",
        "ui_icons": "Content/UI",
        "ui_panels": "Content/UI",
        "ui_portraits": "Content/UI",
        "characters_static": "Content/Models",
        "enemies_static": "Content/Models",
        "bundles": "Content/Bundles",
    },
    "prompts": {
        "materials": ["ps2 jrpg wet stone", "ps2 jrpg ancient brick"],
        "terrain": ["ps2 jrpg forest ground", "ps2 jrpg desert ground"],
        "tilesets": ["ps2 jrpg overworld tileset", "ps2 jrpg dungeon tileset"],
        "props": ["ps2 jrpg treasure chest", "ps2 jrpg merchant crate"],
        "architecture": ["ps2 jrpg stone pillar", "ps2 jrpg temple arch"],
        "foliage": ["ps2 jrpg forest tree", "ps2 jrpg bush"],
        "items": ["ps2 jrpg potion", "ps2 jrpg sword"],
        "decal": ["ps2 jrpg rune decal", "ps2 jrpg sign decal"],
        "ui_icons": ["ps2 jrpg quest icon", "ps2 jrpg shop icon"],
        "ui_panels": ["ps2 jrpg inventory panel", "ps2 jrpg dialog box"],
        "ui_portraits": ["ps2 jrpg hero portrait", "ps2 jrpg knight portrait"],
        "characters_static": ["ps2 jrpg npc humanoid", "ps2 jrpg merchant npc"],
        "enemies_static": ["ps2 jrpg wolf enemy", "ps2 jrpg beast enemy"],
    },
}
