from __future__ import annotations

GAME_REWRITTEN_BUNDLE_RECIPE = {
    "name": "full_static",
    "style_profile": "ps2_ff7_ff12_highest_quality_ps2",
    "required_packs": [
        "material_pack",
        "biome_pack",
        "tileset_pack",
        "prop_pack",
        "architecture_pack",
        "foliage_pack",
        "item_pack",
        "decal_pack",
        "ui_icon_pack",
        "ui_panel_pack",
        "ui_portrait_pack",
        "character_static_pack",
        "enemy_static_pack",
    ],
    "content_targets": {
        "materials": "Content/Materials",
        "terrain": "Content/Textures",
        "tilesets": "Content/World",
        "props": "Content/Models",
        "architecture": "Content/Models",
        "foliage": "Content/Models",
        "items": "Content/Models",
        "decals": "Content/Textures",
        "ui_icons": "Content/UI",
        "ui_panels": "Content/UI",
        "ui_portraits": "Content/UI",
        "characters_static": "Content/Models",
        "enemies_static": "Content/Models",
        "bundles": "Content/Bundles",
    },
    "prompts": {
        "materials": [
            "ps2 jrpg wet stone",
            "ps2 jrpg ancient brick",
            "ps2 jrpg sacred temple marble",
            "ps2 jrpg corrupted ruin basalt",
            "ps2 jrpg imperial fortress steel",
            "ps2 jrpg rebel outpost wood",
            "ps2 jrpg royal palace gold trim marble",
            "ps2 jrpg highland granite moss",
            "ps2 jrpg coastal driftwood weathered",
            "ps2 jrpg volcanic obsidian scorched",
            "ps2 jrpg crystal shrine glowing mythril",
            "ps2 jrpg wasteland cracked clay",
            "ps2 jrpg dungeon damp limestone",
            "ps2 jrpg snowfield frost-bitten granite",
            "ps2 jrpg ancient civilization carved jade",
            "ps2 jrpg port city salt-worn timber",
            "ps2 jrpg swamp bog-rotted bark",
            "ps2 jrpg sacred relic gilded stone",
            "ps2 jrpg underground cave slick obsidian",
            "ps2 jrpg capital city polished travertine",
        ],
        "terrain": [
            "ps2 jrpg forest ground",
            "ps2 jrpg desert ground",
            "ps2 jrpg coastal cliff path",
            "ps2 jrpg highland moss path",
            "ps2 jrpg volcanic ash road",
            "ps2 jrpg crystal shrine floor",
            "ps2 jrpg overworld grass plain",
            "ps2 jrpg sacred ruin stone floor",
            "ps2 jrpg imperial city cobblestone",
            "ps2 jrpg dungeon carved rock floor",
            "ps2 jrpg snowfield icy tundra path",
            "ps2 jrpg port dock wooden planks",
            "ps2 jrpg highland meadow earth trail",
            "ps2 jrpg swamp muddy bog ground",
            "ps2 jrpg capital city plaza stone",
            "ps2 jrpg ruins overgrown grass cracks",
            "ps2 jrpg cave damp rock surface",
            "ps2 jrpg wasteland parched earth flat",
            "ps2 jrpg ancient road carved marble tile",
            "ps2 jrpg fort courtyard gravel bed",
        ],
        "tilesets": [
            "ps2 jrpg overworld tileset",
            "ps2 jrpg dungeon tileset",
            "ps2 jrpg imperial city tileset",
            "ps2 jrpg port town tileset",
            "ps2 jrpg sacred ruins tileset",
            "ps2 jrpg volcanic wasteland tileset",
            "ps2 jrpg highland snowfield tileset",
            "ps2 jrpg forest wilderness tileset",
            "ps2 jrpg rebel camp tileset",
            "ps2 jrpg royal palace interior tileset",
            "ps2 jrpg coastal harbor tileset",
            "ps2 jrpg crystal sanctum tileset",
            "ps2 jrpg swamp marshland tileset",
            "ps2 jrpg underground cave tileset",
            "ps2 jrpg highland fortress tileset",
            "ps2 jrpg ancient civilized ruins tileset",
            "ps2 jrpg desert oasis town tileset",
            "ps2 jrpg arena encounter tileset",
            "ps2 jrpg river delta tileset",
            "ps2 jrpg capital city market tileset",
        ],
        "props": [
            "ps2 jrpg treasure chest",
            "ps2 jrpg merchant crate",
            "ps2 jrpg shrine save crystal pedestal",
            "ps2 jrpg rebel camp supply barrel",
            "ps2 jrpg imperial outpost signal brazier",
            "ps2 jrpg ancient ruin stone tablet",
            "ps2 jrpg port harbor mooring post",
            "ps2 jrpg royal banquet table",
            "ps2 jrpg highland campfire stones",
            "ps2 jrpg dungeon iron torch sconce",
            "ps2 jrpg market lantern post",
            "ps2 jrpg corrupted ruin altar fragment",
            "ps2 jrpg town square stone well",
            "ps2 jrpg plaza marble fountain",
            "ps2 jrpg hero memorial statue plinth",
            "ps2 jrpg crossroads wooden sign post",
            "ps2 jrpg battlefield rubble pile",
            "ps2 jrpg ice cave crystal formation",
            "ps2 jrpg harbor boat mooring marker",
            "ps2 jrpg enemy lair spawn marker",
        ],
        "architecture": [
            "ps2 jrpg stone pillar",
            "ps2 jrpg temple arch",
            "ps2 jrpg imperial gate wall module",
            "ps2 jrpg port city bridge support",
            "ps2 jrpg sacred sanctum altar frame",
            "ps2 jrpg ancient ruin obelisk",
            "ps2 jrpg royal palace ornate column",
            "ps2 jrpg fortress tower bastion",
            "ps2 jrpg highland stone wall section",
            "ps2 jrpg rebel bunker entrance frame",
            "ps2 jrpg crystal shrine gateway",
            "ps2 jrpg dungeon sealed ruin gateway",
            "ps2 jrpg imperial city defensive rampart wall",
            "ps2 jrpg capital gatehouse fortified entry",
            "ps2 jrpg highland watchtower lookout",
            "ps2 jrpg market arcade arch bazaar",
            "ps2 jrpg sacred temple ceremonial steps",
            "ps2 jrpg imperial dungeon iron gate",
            "ps2 jrpg ancient bridge stone arch span",
            "ps2 jrpg fortress wall tower parapet",
        ],
        "foliage": [
            "ps2 jrpg forest tree",
            "ps2 jrpg bush",
            "ps2 jrpg highland cedar tree",
            "ps2 jrpg coastal palm tree",
            "ps2 jrpg sacred grove crystal shrub",
            "ps2 jrpg volcanic deadwood brush",
            "ps2 jrpg overworld meadow flower cluster",
            "ps2 jrpg swamp gnarled tree",
            "ps2 jrpg ruins overgrown ivy bush",
            "ps2 jrpg snowfield frost fern",
            "ps2 jrpg desert scrub cactus",
            "ps2 jrpg dungeon cave fungus cluster",
            "ps2 jrpg snowfield snow pine conifer",
            "ps2 jrpg marsh wetland reed sedge",
            "ps2 jrpg sacred ancient fern frond",
            "ps2 jrpg volcanic obsidian rock cluster",
            "ps2 jrpg coastal reef coral formation",
            "ps2 jrpg highland heather moorland shrub",
            "ps2 jrpg forest underbrush thorn cluster",
            "ps2 jrpg sacred grove willow draping tree",
        ],
        "items": [
            "ps2 jrpg potion",
            "ps2 jrpg sword",
            "ps2 jrpg phoenix relic token",
            "ps2 jrpg crystal charm",
            "ps2 jrpg imperial insignia",
            "ps2 jrpg rebel field kit",
            "ps2 jrpg ancient summon relic orb",
            "ps2 jrpg holy staff icon mesh",
            "ps2 jrpg dark blade corrupted relic",
            "ps2 jrpg highland ranger bow",
            "ps2 jrpg port trade cargo pouch",
            "ps2 jrpg royal crest medallion",
            "ps2 jrpg imperial guard shield",
            "ps2 jrpg knight plate armor chestpiece",
            "ps2 jrpg sacred signet ring",
            "ps2 jrpg elemental essence gem jewel",
            "ps2 jrpg longbow rebel scout",
            "ps2 jrpg ancient relic crystal vial",
            "ps2 jrpg dungeon key carved stone",
            "ps2 jrpg highland field ration supply pack",
        ],
        "decals": [
            "ps2 jrpg rune decal",
            "ps2 jrpg sign decal",
            "ps2 jrpg sacred crest emblem",
            "ps2 jrpg corrupted sigil mark",
            "ps2 jrpg imperial banner insignia",
            "ps2 jrpg rebel resistance glyph",
            "ps2 jrpg ancient civilization floor rune",
            "ps2 jrpg royal coat of arms",
            "ps2 jrpg crystal shrine deity crest",
            "ps2 jrpg dungeon warning skull mark",
            "ps2 jrpg port cargo stamp brand",
            "ps2 jrpg wasteland scavenger territory mark",
            "ps2 jrpg sacred shrine phoenix emblem",
            "ps2 jrpg capital city heraldry banner",
            "ps2 jrpg rebel faction spray mark",
            "ps2 jrpg dungeon faction territory marker",
            "ps2 jrpg ancient map floor mosaic",
            "ps2 jrpg imperial seal official stamp",
            "ps2 jrpg cursed zone hazard glyph",
            "ps2 jrpg summon circle magic rune",
        ],
        "ui_icons": [
            "ps2 jrpg quest icon",
            "ps2 jrpg shop icon",
            "ps2 jrpg save crystal icon",
            "ps2 jrpg summon relic icon",
            "ps2 jrpg imperial faction icon",
            "ps2 jrpg rebel faction icon",
            "ps2 jrpg world map region marker icon",
            "ps2 jrpg battle status effect icon",
            "ps2 jrpg equipment slot icon",
            "ps2 jrpg key item relic icon",
            "ps2 jrpg sacred shrine blessing icon",
            "ps2 jrpg corrupted zone warning icon",
            "ps2 jrpg hp gauge icon",
            "ps2 jrpg mp gauge icon",
            "ps2 jrpg limit break ready icon",
            "ps2 jrpg elemental fire skill icon",
            "ps2 jrpg elemental ice skill icon",
            "ps2 jrpg elemental lightning skill icon",
            "ps2 jrpg party leader marker icon",
            "ps2 jrpg world map warp point icon",
        ],
        "ui_panels": [
            "ps2 jrpg inventory panel",
            "ps2 jrpg dialog box",
            "ps2 jrpg world map panel",
            "ps2 jrpg quest log frame",
            "ps2 jrpg imperial command hud",
            "ps2 jrpg rebel camp hud",
            "ps2 jrpg character status panel",
            "ps2 jrpg battle command menu",
            "ps2 jrpg region travel select panel",
            "ps2 jrpg shop trade interface panel",
            "ps2 jrpg sacred shrine blessing menu",
            "ps2 jrpg summon call interface panel",
            "ps2 jrpg party formation screen frame",
            "ps2 jrpg battle victory results panel",
            "ps2 jrpg inn rest menu frame",
            "ps2 jrpg skill learn ability panel",
            "ps2 jrpg game over screen frame",
            "ps2 jrpg title screen hud frame",
            "ps2 jrpg world region transition panel",
            "ps2 jrpg limit break activation panel",
        ],
        "ui_portraits": [
            "ps2 jrpg hero portrait",
            "ps2 jrpg knight portrait",
            "ps2 jrpg mage portrait",
            "ps2 jrpg rogue portrait",
            "ps2 jrpg imperial captain portrait",
            "ps2 jrpg rebel leader portrait",
            "ps2 jrpg shrine oracle portrait",
            "ps2 jrpg merchant elder portrait",
            "ps2 jrpg corrupted villain portrait",
            "ps2 jrpg highland clan chief portrait",
            "ps2 jrpg port navigator portrait",
            "ps2 jrpg royal advisor portrait",
            "ps2 jrpg innkeeper portrait",
            "ps2 jrpg blacksmith portrait",
            "ps2 jrpg sage scholar portrait",
            "ps2 jrpg thief bandit portrait",
            "ps2 jrpg rebel priest portrait",
            "ps2 jrpg ancient elder portrait",
            "ps2 jrpg enemy warlord bust portrait",
            "ps2 jrpg summon deity card portrait",
        ],
        "characters_static": [
            "ps2 jrpg npc humanoid",
            "ps2 jrpg merchant npc",
            "ps2 jrpg imperial guard npc",
            "ps2 jrpg rebel scout npc",
            "ps2 jrpg shrine priest npc",
            "ps2 jrpg port town villager npc",
            "ps2 jrpg highland ranger npc",
            "ps2 jrpg royal court advisor npc",
            "ps2 jrpg ruins archaeologist npc",
            "ps2 jrpg corrupted cultist npc",
            "ps2 jrpg inn keeper npc",
            "ps2 jrpg elder village chief npc",
            "ps2 jrpg knight paladin npc",
            "ps2 jrpg sage mystic scholar npc",
            "ps2 jrpg blacksmith smith npc",
            "ps2 jrpg mage wizard arcanist npc",
            "ps2 jrpg thief rogue bandit npc",
            "ps2 jrpg capital city soldier guard npc",
            "ps2 jrpg sacred shrine acolyte npc",
            "ps2 jrpg wasteland survivor npc",
        ],
        "enemies_static": [
            "ps2 jrpg wolf enemy",
            "ps2 jrpg beast enemy",
            "ps2 jrpg corrupted ruin fiend enemy",
            "ps2 jrpg imperial war hound enemy",
            "ps2 jrpg volcanic drake enemy",
            "ps2 jrpg undead temple sentinel enemy",
            "ps2 jrpg highland mountain troll enemy",
            "ps2 jrpg coastal sea serpent enemy",
            "ps2 jrpg wasteland bandit raider enemy",
            "ps2 jrpg corrupted mage construct enemy",
            "ps2 jrpg dungeon golem sentinel enemy",
            "ps2 jrpg sacred grove corrupted spirit enemy",
            "ps2 jrpg stone golem enemy",
            "ps2 jrpg fire elemental enemy",
            "ps2 jrpg shadow fiend demon enemy",
            "ps2 jrpg dragon wyrm wyvern enemy",
            "ps2 jrpg revenant wraith phantom enemy",
            "ps2 jrpg basilisk serpent enemy",
            "ps2 jrpg undead revenant warrior enemy",
            "ps2 jrpg imperial war construct sentinel enemy",
        ],
    },
}
